# Generated by Django 5.0.1 on 2024-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
    ]
