# Generated by Django 5.0.1 on 2024-02-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybase', '0003_topic_created_topic_updated_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
